# knowledge-incorporation/src/rl/reward.py
import zmq
import json
import time

# Global ZMQ context and socket
context = None
socket = None

def initialize_reward_client(port: int = 5555):
    """
    Initializes the ZMQ client to connect to the TTT server.

    Args:
        port (int): The port number of the TTT server.
    """
    global context, socket
    if socket is None:
        print(f"Initializing ZMQ client to connect to port {port}...")
        context = zmq.Context()
        socket = context.socket(zmq.REQ)
        socket.connect(f"tcp://localhost:{port}")

def get_reward(prompt: str, generated_completion: str) -> float:
    """
    Sends a prompt and a generated completion to the TTT server and gets the reward.

    Args:
        prompt (str): The original prompt (state).
        generated_completion (str): The completion generated by the Actor (action).

    Returns:
        The mean_gain from the TTT server, which serves as the reward.
    """
    global socket
    if socket is None:
        raise ConnectionError("Reward client is not initialized. Call initialize_reward_client() first.")

    try:
        # Construct the message to send to the server
        # This needs to match the format expected by TTT_server_mlx.py
        message = {
            "prompt": prompt,
            "completion": generated_completion,
            # We can add other parameters here if needed by the server
            "eval_rounds": 1, 
            "train_kwargs": {}
        }

        # Send the request
        socket.send_json(message)

        # Wait for the reply
        response = socket.recv_json()

        # The reward is the mean_gain
        reward = response.get("mean_gain", 0.0)
        return float(reward)

    except Exception as e:
        print(f"Error communicating with TTT server: {e}")
        # Return a neutral reward in case of an error
        return 0.0

def close_reward_client():
    """
    Closes the ZMQ socket and context.
    """
    global context, socket
    if socket:
        socket.close()
        context.term()
        socket = None
        context = None
        print("ZMQ client closed.")

if __name__ == '__main__':
    # Example of how to use the reward client
    # Make sure the TTT_server_mlx.py is running in another terminal first!
    
    try:
        initialize_reward_client()

        # Create a dummy prompt and completion for testing
        dummy_prompt = "Title: Test\n\nContext: This is a test.\n\n---\n\nQuestion: What is this?\n\nAnswer:"
        dummy_completion = "This is a simple test of the reward system."

        print("Sending a test request to the TTT server...")
        reward = get_reward(dummy_prompt, dummy_completion)
        print(f"Received reward: {reward}")

    finally:
        close_reward_client()
