# knowledge-incorporation/src/rl/reward.py
import zmq
import json
import time
import re

# Global ZMQ context and socket
context = None
socket = None

def initialize_reward_client(port: int = 5555):
    """
    Initializes the ZMQ client to connect to the TTT server.

    Args:
        port (int): The port number of the TTT server.
    """
    global context, socket
    if socket is None:
        print(f"Initializing ZMQ client to connect to port {port}...")
        context = zmq.Context()
        socket = context.socket(zmq.REQ)
        # Increase timeout further since TTT operations can take very long
        socket.setsockopt(zmq.RCVTIMEO, 180000)  # 3 minutes
        socket.setsockopt(zmq.SNDTIMEO, 30000)   # 30 seconds for sending
        socket.connect(f"tcp://localhost:{port}")

def get_reward(prompt: str, generated_completion: str, gold_answer: str = None, max_retries: int = 3) -> float:
    """
    Sends a prompt and a generated completion to the TTT server and gets the reward.
    Implements retry logic to handle server crashes.

    Args:
        prompt (str): The original prompt (state).
        generated_completion (str): The completion generated by the Actor (action).
        gold_answer (str): The correct answer for evaluation (optional).
        max_retries (int): Maximum number of retry attempts.

    Returns:
        The adapter_gain from the TTT server, which serves as the reward.
    """
    global socket, context
    
    for attempt in range(max_retries):
        try:
            if socket is None:
                raise ConnectionError("Reward client is not initialized. Call initialize_reward_client() first.")

            # --- 1. Prepare data in the format the server expects ---
            # Parse the title from the prompt
            title_match = re.search(r"Title:\s*(.*?)\n\n", prompt, re.DOTALL)
            title = title_match.group(1).strip() if title_match else "Unknown"
            
            # Create training sequence in the format the server expects
            training_sequence = f"{title}\n{generated_completion}"
            train_sequences = [training_sequence]

            # Parse the prompt format for eval_questions
            context_match = re.search(r"Context:\s*(.*?)\n\n---\n\n", prompt, re.DOTALL)
            question_match = re.search(r"Question:\s*(.*?)\n\nAnswer:", prompt, re.DOTALL)
            
            if not (title_match and context_match and question_match):
                print("Warning: Could not parse prompt structure. Evaluation may be inaccurate.")
                eval_questions = []
            else:
                # FIXED: Use the provided gold answer if available
                eval_questions = [{
                    "title": title,
                    "context": context_match.group(1).strip(),
                    "question": question_match.group(1).strip(),
                    "answer": gold_answer if gold_answer else ""  # Use gold answer if provided
                }]

            # --- 2. Construct the message ---
            message = {
                "train_sequences": train_sequences,
                "eval_questions": eval_questions,
                "finetune_epochs": 1,  # Reduced from 3 to 1 for much faster TTT
                "lora_rank": 8,
            }

            print(f"Attempt {attempt + 1}/{max_retries}: Sending to TTT server...")
            print(f"  - Train sequences: {len(train_sequences)} items")
            print(f"  - Eval questions: {len(eval_questions)} items")
            if eval_questions:
                print(f"  - Question: {eval_questions[0]['question']}")
                print(f"  - Gold answer: {eval_questions[0]['answer']}")  # Show gold answer in logs

            # Send the request
            socket.send_json(message)
            print("  - Request sent, waiting for response...")

            # Wait for the reply
            response = socket.recv_json()
            print("  - Response received successfully!")

            # --- 3. Extract reward ---
            if "error" in response:
                print(f"Server returned an error: {response['error']}")
                return 0.0

            reward = response.get("adapter_gain", 0.0)
            
            print(
                f"Server Response -> "
                f"Baseline Acc: {response.get('baseline_accuracy', 'N/A'):.3f}, "
                f"Adapter Acc: {response.get('adapter_accuracy', 'N/A'):.3f}, "
                f"Gain (Reward): {reward:.3f}"
            )
            return float(reward)

        except zmq.Again:
            print(f"  - Timeout on attempt {attempt + 1}. TTT server may have crashed.")
            if attempt < max_retries - 1:
                print("  - Attempting to reconnect...")
                _reconnect_socket()
                time.sleep(2)  # Wait before retry
            else:
                print("  - Max retries reached. Returning 0.0 reward.")
                return 0.0
                
        except Exception as e:
            print(f"  - Error on attempt {attempt + 1}: {e}")
            if attempt < max_retries - 1:
                print("  - Attempting to reconnect...")
                _reconnect_socket()
                time.sleep(2)
            else:
                print("  - Max retries reached. Returning 0.0 reward.")
                return 0.0

    return 0.0

def preprocess_reward(raw_reward: float, completion: str) -> float:
    """
    Preprocesses the raw reward to improve learning signal.
    
    Args:
        raw_reward: Raw reward from TTT server (-1.0 to 1.0)
        completion: The generated completion string
    
    Returns:
        Processed reward with better learning signal
    """
    # Scale the reward to be more significant
    scaled_reward = raw_reward * 2.0  # Scale from [-1,1] to [-2,2]
    
    # Add completion quality bonuses/penalties
    completion_len = len(completion.strip())
    
    # Penalty for very short completions (likely low quality)
    if completion_len < 20:
        scaled_reward -= 0.5
        
    # Penalty for very long completions (likely repetitive/off-topic)
    elif completion_len > 500:
        scaled_reward -= 0.3
        
    # Small bonus for reasonable length completions
    elif 50 <= completion_len <= 200:
        scaled_reward += 0.2
    
    # Penalty for repetitive text (simple heuristic)
    words = completion.lower().split()
    if len(words) > 10:
        unique_words = len(set(words))
        repetition_ratio = unique_words / len(words)
        if repetition_ratio < 0.5:  # More than 50% repeated words
            scaled_reward -= 0.4
    
    # Clamp final reward to reasonable range
    return max(-3.0, min(3.0, scaled_reward))

def _reconnect_socket():
    """Helper function to reconnect the ZMQ socket."""
    global socket, context
    try:
        if socket:
            socket.close()
        socket = context.socket(zmq.REQ)
        socket.setsockopt(zmq.RCVTIMEO, 180000)  # 3 minutes
        socket.setsockopt(zmq.SNDTIMEO, 30000)   # 30 seconds
        socket.connect(f"tcp://localhost:5555")
        print("  - Socket reconnected")
    except Exception as e:
        print(f"  - Failed to reconnect socket: {e}")
        socket = None

def close_reward_client():
    """
    Closes the ZMQ socket and context.
    """
    global context, socket
    if socket:
        socket.close()
        context.term()
        socket = None
        context = None
        print("ZMQ client closed.")

if __name__ == '__main__':
    # Example of how to use the reward client
    # Make sure the TTT_server_mlx.py is running in another terminal first!
    
    try:
        initialize_reward_client()

        # Create a dummy prompt and completion for testing
        dummy_prompt = "Title: ZMQ Reward System\n\nContext: The client sends a request to the server to get a reward.\n\n---\n\nQuestion: What does the client send to the server?\n\nAnswer:"
        dummy_completion = "The client sends a JSON object containing training sequences and evaluation questions."

        print("Sending a test request to the TTT server...")
        reward = get_reward(dummy_prompt, dummy_completion)
        print(f"\nFinal received reward: {reward}")

    finally:
        close_reward_client()
